### ISSUE TITLE
rawurlencode() expects parameter 1 to be string, bool given in Escaper.php:246

### ISSUE THREAD

**Issue by purpletreesoft** [laminas/laminas-escaper#24]
The latest version passes int argument to rawurlencode, where string is expected.

problem is at line 246:

`return rawurlencode($string);
`

possible solution:

`return rawurlencode(strval($string));`

**Comment by purpletreesoft** [comment]
This issue was observed in Magento 2 CE, when the latest Laminas was pulled.

**Comment by purpletreesoft** [comment]
I see another issue related to strict checks introduced. Perhaps that commit fixes this issue too?

**Comment by froschdesign** [comment]
Duplicate of #20 

See also: https://github.com/laminas/laminas-escaper/issues/21#issuecomment-868542534
