### ISSUE TITLE
Escaper.php - BC break by introduction of strict types

### ISSUE THREAD

**Issue by griesi007** [laminas/laminas-escaper#26]
### BC Break Report

Declaring strict on Escaper.php lately introduced BC Breaks as htmlspecialchars fails now if a type not beeing a string is escaped. So far other primitive types such as int, float, null were accepted and escaped which made Escaper especially with the view helpers easy to use . This change also lead to escaping beeing more complicated as it should be. In my opinion Escaper should be more permissive regarding the accepted types. E.g. certain types null, int, float ... could easily be handled and escaped by converting them to strings.  

|    Q        |   A
|------------ | ------
| Version     | 2.8.0

**Comment by griesi007** [comment]
Duplicate of #20

See also: #21 (comment)

**Comment by froschdesign** [comment]
@griesi007 
Please see also the [release notes of version 2.8.0](https://github.com/laminas/laminas-escaper/releases/tag/2.8.0).
