### ISSUE TITLE
Installing under PHP 8.2

### ISSUE THREAD

**Issue by seth-xdam** [laminas/laminas-escaper#36]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.9.0, 2.10.0, 2.11.x-dev

#### Summary
I want to install the latest version of Laminas Escaper (2.10.0) in a PHP 8.2rc3 environment. The current composer.json says it requires PHP `^7.4 || ~8.0.0 || ~8.1.0`, so it won't install. The latest dev version, `2.11.x-dev`, is the same.

The most recent version that WILL install is 2.5.2 (requires `php >=5.5`), and that is certainly not more compatible than 2.10 - it just has a more vague `requires` statement.

Unless there are pending incompatibilities, PHP 8.2 should be added to the list of supported versions in preparation for its expected release late next month.

#### Current behavior

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laminas/laminas-escaper ^2.10.0 -> satisfiable by laminas/laminas-escaper[2.10.0].
    - laminas/laminas-escaper 2.10.0 requires php ^7.4 || ~8.0.0 || ~8.1.0 -> your php version (8.2.0RC3) does not satisfy that requirement.
```

#### How to reproduce

1. Install PHP 8.2 (I used the Remi repository following [these instructions](https://blog.remirepo.net/post/2022/02/07/Install-PHP-8.1-on-Fedora-RHEL-CentOS-Alma-Rocky-or-other-clone), but using `php82` instead of `php81`)
2. Add `"laminas/laminas-escaper": "^2.10.0"` to the `require` block of composer.json
3. Run `composer update`

#### Expected behavior

For composer to install laminas-escaper 2.10.0

**Comment by Ocramius** [comment]
Correct, PHP 8.2 is not yet in the supported dependency range.

That is intentional.

**Comment by Ocramius** [comment]
To clarify: PHP 8.2 support will come once it's fully tested on the repository. For now, use `--ignore-platform-req=php` **if** you know what you are doing.

**Comment by seth-xdam** [comment]
Thanks for the clarification. Is there a rough estimate of the timeframe between PHP 8.2 being officially released and when testing will be completed? (hours, days, or weeks?)

**Comment by Ocramius** [comment]
Whenever it's ready :)

You can help by figuring out how we can configure https://github.com/laminas/.github/ to have @renovatebot bump these dependency ranges automatically for us.
