### ISSUE TITLE
Support for PHP 8.3

### ISSUE THREAD

**Issue by distantnative** [laminas/laminas-escaper#48]
Would be great if this library could support PHP 8.3 🙏

**Comment by Ocramius** [comment]
All laminas packages will be updated in due time: we already automate dependency upgrades.

**Comment by distantnative** [comment]
@Ocramius Thanks for the quick roll and good news! Maybe the issue shouldn't be closed yet? So others can find the info too and only close it when it has been released?

**Comment by Ocramius** [comment]
Fine with keeping it open, just trying to reduce clutter, since it's a ton of noise for maintainers otherwise

**Comment by Ocramius** [comment]
Implented in #49
