### ISSUE TITLE
2.13.0 broke semver conventions by dropping PHP 7.4 and 8.0 support

### ISSUE THREAD

**Issue by sc0ttdav3y** [laminas/laminas-escaper#50]
### BC Break Report

Hi, many thanks for your work on this project. 

In my case, this project is a dependency of a dependency and I'm working on a project where we're currently unable to upgrade from an older version of PHP 7.4.  I know, we shouldn't be in this position, but still, here we are. Given Laminas is where many ZF refugees went to, we may not be alone.

Overnight we found this package had [dropped PHP 7.4 support](https://github.com/laminas/laminas-escaper/pull/46/files) but used a minor version bump. 

According to [the Semver standard](https://semver.org/#spec-item-7), this should be a backward _incompatible_ change and therefore should use a major version increment.

We'll pin to the previous release to resolve for now, but I figure this report can give you an insight into where some of your users' projects and environments are at.

Again, thanks for your work and sorry to be the guy that brings this up.

Cheers, Scott

|    Q        |   A
|------------ | ------
| Version     | 2.13.0

#### Summary

New minimum PHP version breaks BC with older projects.

#### Previous behavior

The package ran on PHP 7.4

#### Current behavior

The package prevents PHP 7.4 projects from working.

#### How to reproduce

`composer update` :-)

**Comment by Xerkus** [comment]
Changing dependency requirements does NOT change a public api for the package. Much less a breaking change. No code running on actually supported php version needs any changes to update to a new minor. 

Please see https://github.com/semver/semver/blob/38a25311c9933d0fd8b9b017866b8be9a405f4ec/semver.md#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api
